# Generated by Django 4.2.3 on 2023-07-30 19:02

import app_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[app_account.models.phone_validate]),
        ),
    ]
